export const DISPUTE_MONTHS: any[] = [
    {
        "name":"Junho/Julho",
        "id":8,
        "players":[
            {
                "name":"Willame",
                "team":"FlaMegue FC",
                "points":360,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/9b/51/14/004c2515ba-6c25-4871-883c-c00ed77e7e9b20180413205114",
                "details":[
                    {
                        "round":9,
                        "points":106.72
                    },
                    {
                        "round":10,
                        "points":73.6
                    },
                    {
                        "round":11,
                        "points":104.65
                    },
                    {
                        "round":12,
                        "points":75.03
                    }
                ]
            },
            {
                "name":"Cleber Ramos",
                "team":"47 DO SEGUNDO TEMPO FC",
                "points":355.36,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/71/33/22/00716ed07e-6578-472f-955c-32ebda49777120180413133322",
                "details":[
                    {
                        "round":9,
                        "points":108.22
                    },
                    {
                        "round":10,
                        "points":91.2
                    },
                    {
                        "round":11,
                        "points":84.11
                    },
                    {
                        "round":12,
                        "points":71.83
                    }
                ]
            },
            {
                "name":"Caio Batista",
                "team":"Batista S.C",
                "points":350.44,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_101/escudo/ea/12/37/006d268f25-c0b7-4761-b3ff-8e3a9d8c0dea20180323201237",
                "details":[
                    {
                        "round":9,
                        "points":104.32
                    },
                    {
                        "round":10,
                        "points":87.62
                    },
                    {
                        "round":11,
                        "points":88.85
                    },
                    {
                        "round":12,
                        "points":69.65
                    }
                ]
            },
            {
                "name":"José Carlos",
                "team":"Boa Viagem E. Clube",
                "points":349.92,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/40/32/34/00bf8f80da-4356-466e-a062-da07b4b1a34020180410103234",
                "details":[
                    {
                        "round":9,
                        "points":84.62
                    },
                    {
                        "round":10,
                        "points":74.52
                    },
                    {
                        "round":11,
                        "points":99.45
                    },
                    {
                        "round":12,
                        "points":91.33
                    }
                ]
            },
            {
                "name":"Victor Bessa",
                "team":"Bessa CSC",
                "points":348.02,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/dc/33/02/00ce9bd458-5b83-48c7-a0c0-a4710fc141dc20180411103302",
                "details":[
                    {
                        "round":9,
                        "points":90.92
                    },
                    {
                        "round":10,
                        "points":85.42
                    },
                    {
                        "round":11,
                        "points":74.04
                    },
                    {
                        "round":12,
                        "points":97.64
                    }
                ]
            },
            {
                "name":"Marcelo Pascoal",
                "team":"Celim Team",
                "points":346.51,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/73/08/40/00524fac54-80b2-404a-af8e-685d2d16107320180410140840",
                "details":[
                    {
                        "round":9,
                        "points":110.22
                    },
                    {
                        "round":10,
                        "points":83.42
                    },
                    {
                        "round":11,
                        "points":67.52
                    },
                    {
                        "round":12,
                        "points":85.35
                    }
                ]
            },
            {
                "name":"Danielson Filho",
                "team":"Raimundões FC",
                "points":333.42,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_105/escudo/fb/40/17/0044d2aa58-33cc-4c54-a068-585cd48c18fb20180406094017",
                "details":[
                    {
                        "round":9,
                        "points":87.92
                    },
                    {
                        "round":10,
                        "points":80.02
                    },
                    {
                        "round":11,
                        "points":89.35
                    },
                    {
                        "round":12,
                        "points":76.13
                    }
                ]
            },
            {
                "name":"Victor Gomes",
                "team":"Victor Gomes Sporting Club",
                "points":333.02,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_109/escudo/63/43/03/00cc0f22de-56ce-4cd3-b0d5-a0d7e4717f6320180412174303",
                "details":[
                    {
                        "round":9,
                        "points":101.82
                    },
                    {
                        "round":10,
                        "points":72.52
                    },
                    {
                        "round":11,
                        "points":95.85
                    },
                    {
                        "round":12,
                        "points":62.83
                    }
                ]
            },
            {
                "name":"Ronilson Costa",
                "team":"Phode Chorarr FC",
                "points":332.14,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_103/escudo/36/36/53/00f3f60de2-60ef-432d-9695-e924b034033620180326233653",
                "details":[
                    {
                        "round":9,
                        "points":96.12
                    },
                    {
                        "round":10,
                        "points":88.58
                    },
                    {
                        "round":11,
                        "points":64.61
                    },
                    {
                        "round":12,
                        "points":82.83
                    }
                ]
            },
            {
                "name":"Vanduy Sales",
                "team":"Vanduka FC",
                "points":330.92,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/5e/46/05/00f08bd7cf-ca3e-4734-871a-e40a53804b5e20180410154605",
                "details":[
                    {
                        "round":9,
                        "points":77.35
                    },
                    {
                        "round":10,
                        "points":67.32
                    },
                    {
                        "round":11,
                        "points":107.7
                    },
                    {
                        "round":12,
                        "points":78.55
                    }
                ]
            },
            {
                "name":"Márcio Ayres",
                "team":"Down Futball United",
                "points":330.2,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_101/escudo/f6/28/00/008d179c97-48ca-48d2-b579-469a5c2ab7f620180323192800",
                "details":[
                    {
                        "round":9,
                        "points":81.08
                    },
                    {
                        "round":10,
                        "points":71.42
                    },
                    {
                        "round":11,
                        "points":96.31
                    },
                    {
                        "round":12,
                        "points":81.39
                    }
                ]
            },
            {
                "name":"Bruno Dias",
                "team":"Valério Central F. C",
                "points":327.89,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_105/escudo/aa/54/56/00e01a2f6b-9906-4e70-8d91-ec6cc5bad9aa20180406175456",
                "details":[
                    {
                        "round":9,
                        "points":74.42
                    },
                    {
                        "round":10,
                        "points":69.03
                    },
                    {
                        "round":11,
                        "points":87.31
                    },
                    {
                        "round":12,
                        "points":97.13
                    }
                ]
            },
            {
                "name":"Lucas Batista",
                "team":"vovo S.C",
                "points":326.83,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/f6/17/23/00b142cb5a-fdfd-4976-875a-89e6a21cdef620180324211723",
                "details":[
                    {
                        "round":9,
                        "points":87.72
                    },
                    {
                        "round":10,
                        "points":67.72
                    },
                    {
                        "round":11,
                        "points":77.84
                    },
                    {
                        "round":12,
                        "points":93.55
                    }
                ]
            },
            {
                "name":"Karlos Emanuel",
                "team":"Clube Artimanhã",
                "points":322.14,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/71/01/27/006e2380da-4e96-4336-a467-e43ce6f5d67120180411130127",
                "details":[
                    {
                        "round":9,
                        "points":117.74
                    },
                    {
                        "round":10,
                        "points":70.6
                    },
                    {
                        "round":11,
                        "points":85.85
                    },
                    {
                        "round":12,
                        "points":47.95
                    }
                ]
            },
            {
                "name":"Rafael Costa",
                "team":"Ferrimbahçe",
                "points":318.31,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_112/escudo/e6/09/39/001d366c29-9e34-4201-958b-34aa246edfe620180414140939",
                "details":[
                    {
                        "round":9,
                        "points":109.62
                    },
                    {
                        "round":10,
                        "points":62.55
                    },
                    {
                        "round":11,
                        "points":83.51
                    },
                    {
                        "round":12,
                        "points":62.63
                    }
                ]
            },
            {
                "name":"Marcelo Faustino",
                "team":"Palestra Cangaceiro",
                "points":312.89,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/19/09/39/0096e4f1f1-f2b9-4f08-b945-2ac1943bab1920180322150939",
                "details":[
                    {
                        "round":9,
                        "points":103.29
                    },
                    {
                        "round":10,
                        "points":81.42
                    },
                    {
                        "round":11,
                        "points":77.75
                    },
                    {
                        "round":12,
                        "points":50.43
                    }
                ]
            },
            {
                "name":"Elano Matos",
                "team":"Pau Serrado FC",
                "points":312.87,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/82/02/44/007f184c56-0ccd-4ad9-b966-1be4c2af158220180413170244",
                "details":[
                    {
                        "round":9,
                        "points":75.46
                    },
                    {
                        "round":10,
                        "points":84.04
                    },
                    {
                        "round":11,
                        "points":84.04
                    },
                    {
                        "round":12,
                        "points":69.33
                    }
                ]
            },
            {
                "name":"Daniel Oliveira",
                "team":"PIEDADE FCF",
                "points":312.73,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/02/24/25/00a1fc9194-2acd-4579-b6ff-6e936d070b0220180322142425",
                "details":[
                    {
                        "round":9,
                        "points":81.32
                    },
                    {
                        "round":10,
                        "points":75.24
                    },
                    {
                        "round":11,
                        "points":75.24
                    },
                    {
                        "round":12,
                        "points":80.93
                    }
                ]
            },
            {
                "name":"Matheus Batista",
                "team":"Come mosca fc",
                "points":310.12,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/e6/35/18/00c0de3da7-5908-4d60-acff-4b380add5fe620180322133518",
                "details":[
                    {
                        "round":9,
                        "points":79.86
                    },
                    {
                        "round":10,
                        "points":65.42
                    },
                    {
                        "round":11,
                        "points":80.81
                    },
                    {
                        "round":12,
                        "points":84.03
                    }
                ]
            },
            {
                "name":"Victor Santiago",
                "team":"VBSantiago FC",
                "points":307.96,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/82/18/03/001e09f7b4-5047-495a-8634-8d3328be278220180326111803",
                "details":[
                    {
                        "round":9,
                        "points":95.64
                    },
                    {
                        "round":10,
                        "points":66.12
                    },
                    {
                        "round":11,
                        "points":84.25
                    },
                    {
                        "round":12,
                        "points":61.95
                    }
                ]
            },
            {
                "name":"Alberto Perdigão",
                "team":"PerdiCartola F.C",
                "points":302.8,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_111/escudo/15/20/00/000fde8b37-3a24-4acb-8e0c-73d41b9ef71520180414132000",
                "details":[
                    {
                        "round":9,
                        "points":80.08
                    },
                    {
                        "round":10,
                        "points":65.94
                    },
                    {
                        "round":11,
                        "points":72.95
                    },
                    {
                        "round":12,
                        "points":83.83
                    }
                ]
            },
            {
                "name":"Yuri Silva",
                "team":"FutArte FEC",
                "points":302,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/af/39/37/00e85bc1c3-11f6-4945-b966-696c091d20af20180326133937",
                "details":[
                    {
                        "round":9,
                        "points":94.14
                    },
                    {
                        "round":10,
                        "points":79.42
                    },
                    {
                        "round":11,
                        "points":70.71
                    },
                    {
                        "round":12,
                        "points":57.73
                    }
                ]
            },
            {
                "name":"Marciano Araújo",
                "team":"Vovô do Yan",
                "points":299.04,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/fc/43/18/00ad839309-7037-49f9-a6e1-fbff4871b2fc20180322144318",
                "details":[
                    {
                        "round":9,
                        "points":86.04
                    },
                    {
                        "round":10,
                        "points":68.02
                    },
                    {
                        "round":11,
                        "points":68.05
                    },
                    {
                        "round":12,
                        "points":76.93
                    }
                ]
            },
            {
                "name":"Cayo Luiz",
                "team":"C.Luiz",
                "points":297.03,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/f4/51/23/003ad7972e-c85d-4ea0-a979-f373c9815ff420180326185123",
                "details":[
                    {
                        "round":9,
                        "points":33.11
                    },
                    {
                        "round":10,
                        "points":78.02
                    },
                    {
                        "round":11,
                        "points":65.95
                    },
                    {
                        "round":12,
                        "points":119.95
                    }
                ]
            },
            {
                "name":"Diogo",
                "team":"Cearamengofc",
                "points":293.91,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/9f/10/40/00385df8a3-17fd-4936-a6eb-3270855b619f20180326201040",
                "details":[
                    {
                        "round":9,
                        "points":85.56
                    },
                    {
                        "round":10,
                        "points":83.62
                    },
                    {
                        "round":11,
                        "points":54.82
                    },
                    {
                        "round":12,
                        "points":69.91
                    }
                ]
            },
            {
                "name":"Paulo Cristiano",
                "team":"Ragnar Lothbrok 2018",
                "points":290.15,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/9e/48/55/00c8ee0c6a-37ab-40ea-8a28-9b8be9b8649e20180411094855",
                "details":[
                    {
                        "round":9,
                        "points":82.34
                    },
                    {
                        "round":10,
                        "points":74.43
                    },
                    {
                        "round":11,
                        "points":57.55
                    },
                    {
                        "round":12,
                        "points":75.83
                    }
                ]
            },
            {
                "name":"Felipe Phelype",
                "team":"IslandOfCatsFootball",
                "points":286.12,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/3b/30/52/00e363677a-d283-48b2-8f1a-97fee1ada03b20180326223052",
                "details":[
                    {
                        "round":9,
                        "points":74.96
                    },
                    {
                        "round":10,
                        "points":57.42
                    },
                    {
                        "round":11,
                        "points":78.51
                    },
                    {
                        "round":12,
                        "points":75.23
                    }
                ]
            },
            {
                "name":"Daniel Zanata",
                "team":"Zanatinha CFC",
                "points":282.53,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_109/escudo/0a/02/08/00cf4297dc-6402-466b-b246-8a46ee20d50a20180412160208",
                "details":[
                    {
                        "round":9,
                        "points":90.36
                    },
                    {
                        "round":10,
                        "points":63.53
                    },
                    {
                        "round":11,
                        "points":67.81
                    },
                    {
                        "round":12,
                        "points":60.83
                    }
                ]
            },
            {
                "name":"Marcelo Almeida",
                "team":"Camisa10daGavea",
                "points":281.41,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_109/escudo/cd/38/52/0088e74e4f-f38a-4256-8c47-0179c02643cd20180412183852",
                "details":[
                    {
                        "round":9,
                        "points":82.96
                    },
                    {
                        "round":10,
                        "points":43.12
                    },
                    {
                        "round":11,
                        "points":97.02
                    },
                    {
                        "round":12,
                        "points":58.31
                    }
                ]
            },
            {
                "name":"Emival Queiroz",
                "team":"Emival SCCP",
                "points":277.69,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/19/22/55/00d1e5a05d-2d80-4c88-b431-b30d36594c1920180411162255",
                "details":[
                    {
                        "round":9,
                        "points":75.85
                    },
                    {
                        "round":10,
                        "points":67.9
                    },
                    {
                        "round":11,
                        "points":67.9
                    },
                    {
                        "round":12,
                        "points":66.04
                    }
                ]
            },
            {
                "name":"JORGE PEREIRA",
                "team":"JORGEJOH",
                "points":276.58,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/aa/17/03/007dbfde16-dee2-4a0a-abf1-f1f3eedcaaaa20180412131703",
                "details":[
                    {
                        "round":9,
                        "points":81.68
                    },
                    {
                        "round":10,
                        "points":67.42
                    },
                    {
                        "round":11,
                        "points":60.25
                    },
                    {
                        "round":12,
                        "points":67.23
                    }
                ]
            },
            {
                "name":"Ivolnildo",
                "team":"coringao team1",
                "points":275.31,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/3c/35/13/0074655b24-f231-4e24-bd83-1d5c692eda3c20180326183513",
                "details":[
                    {
                        "round":9,
                        "points":62.96
                    },
                    {
                        "round":10,
                        "points":81.08
                    },
                    {
                        "round":11,
                        "points":67.01
                    },
                    {
                        "round":12,
                        "points":64.26
                    }
                ]
            },
            {
                "name":"Daniel Mendes",
                "team":"djmss fc",
                "points":267.27,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/01/40/51/003bc5bc37-a9f7-4c4c-a152-ed225a60d20120180410144051",
                "details":[
                    {
                        "round":9,
                        "points":47.92
                    },
                    {
                        "round":10,
                        "points":50.72
                    },
                    {
                        "round":11,
                        "points":64.84
                    },
                    {
                        "round":12,
                        "points":103.79
                    }
                ]
            },
            {
                "name":"Messias Cezar",
                "team":"Mumbaba Futebol Clube",
                "points":257.99,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_115/escudo/da/42/10/0080bc5722-e087-4531-a3b0-b3d504455cda20180423114210",
                "details":[
                    {
                        "round":9,
                        "points":62.76
                    },
                    {
                        "round":10,
                        "points":41.35
                    },
                    {
                        "round":11,
                        "points":95.62
                    },
                    {
                        "round":12,
                        "points":58.26
                    }
                ]
            },
            {
                "name":"Márcio Fernandes",
                "team":"Gigante Alvinegro MF",
                "points":227.97,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/3b/42/24/00cd21c39d-27f3-453f-96eb-de0bf4c9d13b20180413164224",
                "details":[
                    {
                        "round":9,
                        "points":76.72
                    },
                    {
                        "round":10,
                        "points":56.22
                    },
                    {
                        "round":11,
                        "points":60.84
                    },
                    {
                        "round":12,
                        "points":34.19
                    }
                ]
            },
            {
                "name":"Vanderson Cabral",
                "team":"FC Cara Seca",
                "points":218.49,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/58/27/49/0095a2202b-f659-485c-a073-a8708b2d215820180412132749",
                "details":[
                    {
                        "round":9,
                        "points":55.38
                    },
                    {
                        "round":10,
                        "points":49.82
                    },
                    {
                        "round":11,
                        "points":62.34
                    },
                    {
                        "round":12,
                        "points":50.95
                    }
                ]
            },
            {
                "name":"Fabio Gurgel",
                "team":"FaBayern FC",
                "points":212.48,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/62/39/50/0067cbf8fd-a20c-499e-bef5-f0f5c0ce5b6220180411153950",
                "details":[
                    {
                        "round":9,
                        "points":26.05
                    },
                    {
                        "round":10,
                        "points":69.95
                    },
                    {
                        "round":11,
                        "points":77.04
                    },
                    {
                        "round":12,
                        "points":39.44
                    }
                ]
            },
            {
                "name":"Rennan Batista",
                "team":"Chico e Gunha FC",
                "points":211.07,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_101/escudo/51/03/57/003c06ccac-0b0d-4f74-9433-93c51432475120180323220357",
                "details":[
                    {
                        "round":9,
                        "points":58.72
                    },
                    {
                        "round":10,
                        "points":48.68
                    },
                    {
                        "round":11,
                        "points":48.68
                    },
                    {
                        "round":12,
                        "points":54.99
                    }
                ]
            },
            {
                "name":"Renan Benevides",
                "team":"simple man",
                "points":197.64,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/a5/56/39/0019f298fb-4fc9-47d2-a8e6-b944682db5a520180413145639",
                "details":[
                    {
                        "round":9,
                        "points":53.32
                    },
                    {
                        "round":10,
                        "points":51.14
                    },
                    {
                        "round":11,
                        "points":44.89
                    },
                    {
                        "round":12,
                        "points":48.29
                    }
                ]
            }
        ]
    },
    {
        "name":"Abril/Maio",
        "id":7,
        "players":[
            {
                "name":"Marciano Araújo",
                "team":"Vovô do Yan",
                "points":821.6,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/fc/43/18/00ad839309-7037-49f9-a6e1-fbff4871b2fc20180322144318",
                "details":[
                    {
                        "round":1,
                        "points":113.95
                    },
                    {
                        "round":2,
                        "points":87.45
                    },
                    {
                        "round":3,
                        "points":101.09
                    },
                    {
                        "round":4,
                        "points":107.32
                    },
                    {
                        "round":5,
                        "points":118.02
                    },
                    {
                        "round":6,
                        "points":82.32
                    },
                    {
                        "round":7,
                        "points":85.16
                    },
                    {
                        "round":8,
                        "points":126.29
                    }
                ]
            },
            {
                "name":"Márcio Ayres",
                "team":"Down Futball United",
                "points":772.13,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_101/escudo/f6/28/00/008d179c97-48ca-48d2-b579-469a5c2ab7f620180323192800",
                "details":[
                    {
                        "round":1,
                        "points":113.65
                    },
                    {
                        "round":2,
                        "points":99.78
                    },
                    {
                        "round":3,
                        "points":87.49
                    },
                    {
                        "round":4,
                        "points":75.97
                    },
                    {
                        "round":5,
                        "points":121.22
                    },
                    {
                        "round":6,
                        "points":70.88
                    },
                    {
                        "round":7,
                        "points":96.96
                    },
                    {
                        "round":8,
                        "points":106.18
                    }
                ]
            },
            {
                "name":"Willame",
                "team":"FlaMegue FC",
                "points":739.17,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/9b/51/14/004c2515ba-6c25-4871-883c-c00ed77e7e9b20180413205114",
                "details":[
                    {
                        "round":1,
                        "points":79.67
                    },
                    {
                        "round":2,
                        "points":94.55
                    },
                    {
                        "round":3,
                        "points":103.59
                    },
                    {
                        "round":4,
                        "points":102.08
                    },
                    {
                        "round":5,
                        "points":91.98
                    },
                    {
                        "round":6,
                        "points":56.62
                    },
                    {
                        "round":7,
                        "points":82.79
                    },
                    {
                        "round":8,
                        "points":127.89
                    }
                ]
            },
            {
                "name":"Cleber Ramos",
                "team":"47 DO SEGUNDO TEMPO FC",
                "points":736.28,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/71/33/22/00716ed07e-6578-472f-955c-32ebda49777120180413133322",
                "details":[
                    {
                        "round":1,
                        "points":67.85
                    },
                    {
                        "round":2,
                        "points":64.95
                    },
                    {
                        "round":3,
                        "points":115.62
                    },
                    {
                        "round":4,
                        "points":70.86
                    },
                    {
                        "round":5,
                        "points":93.52
                    },
                    {
                        "round":6,
                        "points":107.32
                    },
                    {
                        "round":7,
                        "points":89.48
                    },
                    {
                        "round":8,
                        "points":126.68
                    }
                ]
            },
            {
                "name":"Matheus Batista",
                "team":"Come mosca fc",
                "points":733.45,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/e6/35/18/00c0de3da7-5908-4d60-acff-4b380add5fe620180322133518",
                "details":[
                    {
                        "round":1,
                        "points":98.45
                    },
                    {
                        "round":2,
                        "points":91.68
                    },
                    {
                        "round":3,
                        "points":103.79
                    },
                    {
                        "round":4,
                        "points":68.42
                    },
                    {
                        "round":5,
                        "points":110.32
                    },
                    {
                        "round":6,
                        "points":90.93
                    },
                    {
                        "round":7,
                        "points":87.38
                    },
                    {
                        "round":8,
                        "points":82.48
                    }
                ]
            },
            {
                "name":"Karlos Emanuel",
                "team":"Clube Artimanhã",
                "points":730.67,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/71/01/27/006e2380da-4e96-4336-a467-e43ce6f5d67120180411130127",
                "details":[
                    {
                        "round":1,
                        "points":93.47
                    },
                    {
                        "round":2,
                        "points":102.18
                    },
                    {
                        "round":3,
                        "points":69.59
                    },
                    {
                        "round":4,
                        "points":53.52
                    },
                    {
                        "round":5,
                        "points":105.22
                    },
                    {
                        "round":6,
                        "points":98.13
                    },
                    {
                        "round":7,
                        "points":92.36
                    },
                    {
                        "round":8,
                        "points":116.2
                    }
                ]
            },
            {
                "name":"Victor Gomes",
                "team":"Victor Gomes Sporting Club",
                "points":726.97,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_109/escudo/63/43/03/00cc0f22de-56ce-4cd3-b0d5-a0d7e4717f6320180412174303",
                "details":[
                    {
                        "round":1,
                        "points":90.55
                    },
                    {
                        "round":2,
                        "points":89.48
                    },
                    {
                        "round":3,
                        "points":73.49
                    },
                    {
                        "round":4,
                        "points":71.66
                    },
                    {
                        "round":5,
                        "points":123.02
                    },
                    {
                        "round":6,
                        "points":94.62
                    },
                    {
                        "round":7,
                        "points":76.86
                    },
                    {
                        "round":8,
                        "points":107.29
                    }
                ]
            },
            {
                "name":"Marcelo Faustino",
                "team":"Palestra Cangaceiro",
                "points":712.72,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/19/09/39/0096e4f1f1-f2b9-4f08-b945-2ac1943bab1920180322150939",
                "details":[
                    {
                        "round":1,
                        "points":83.85
                    },
                    {
                        "round":2,
                        "points":97.28
                    },
                    {
                        "round":3,
                        "points":64.09
                    },
                    {
                        "round":4,
                        "points":99.42
                    },
                    {
                        "round":5,
                        "points":102.62
                    },
                    {
                        "round":6,
                        "points":96.52
                    },
                    {
                        "round":7,
                        "points":76.26
                    },
                    {
                        "round":8,
                        "points":92.68
                    }
                ]
            },
            {
                "name":"Bruno Dias",
                "team":"Valério Central F. C",
                "points":699.57,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_105/escudo/aa/54/56/00e01a2f6b-9906-4e70-8d91-ec6cc5bad9aa20180406175456",
                "details":[
                    {
                        "round":1,
                        "points":99.95
                    },
                    {
                        "round":2,
                        "points":91.58
                    },
                    {
                        "round":3,
                        "points":82.85
                    },
                    {
                        "round":4,
                        "points":106.62
                    },
                    {
                        "round":5,
                        "points":92.72
                    },
                    {
                        "round":6,
                        "points":47.57
                    },
                    {
                        "round":7,
                        "points":79.96
                    },
                    {
                        "round":8,
                        "points":98.32
                    }
                ]
            },
            {
                "name":"Yuri Silva",
                "team":"FutArte FEC",
                "points":693.34,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/af/39/37/00e85bc1c3-11f6-4945-b966-696c091d20af20180326133937",
                "details":[
                    {
                        "round":1,
                        "points":78.15
                    },
                    {
                        "round":2,
                        "points":89.45
                    },
                    {
                        "round":3,
                        "points":102.49
                    },
                    {
                        "round":4,
                        "points":67.26
                    },
                    {
                        "round":5,
                        "points":84.72
                    },
                    {
                        "round":6,
                        "points":86.23
                    },
                    {
                        "round":7,
                        "points":78.26
                    },
                    {
                        "round":8,
                        "points":106.78
                    }
                ]
            },
            {
                "name":"Ivolnildo",
                "team":"coringao team1",
                "points":687.11,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/3c/35/13/0074655b24-f231-4e24-bd83-1d5c692eda3c20180326183513",
                "details":[
                    {
                        "round":1,
                        "points":71.65
                    },
                    {
                        "round":2,
                        "points":83.84
                    },
                    {
                        "round":3,
                        "points":89.59
                    },
                    {
                        "round":4,
                        "points":112.72
                    },
                    {
                        "round":5,
                        "points":116.43
                    },
                    {
                        "round":6,
                        "points":46.08
                    },
                    {
                        "round":7,
                        "points":67.56
                    },
                    {
                        "round":8,
                        "points":99.24
                    }
                ]
            },
            {
                "name":"Danielson Filho",
                "team":"Raimundões FC",
                "points":677.32,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_105/escudo/fb/40/17/0044d2aa58-33cc-4c54-a068-585cd48c18fb20180406094017",
                "details":[
                    {
                        "round":1,
                        "points":92.15
                    },
                    {
                        "round":2,
                        "points":77.88
                    },
                    {
                        "round":3,
                        "points":87.59
                    },
                    {
                        "round":4,
                        "points":68.97
                    },
                    {
                        "round":5,
                        "points":81.96
                    },
                    {
                        "round":6,
                        "points":79.33
                    },
                    {
                        "round":7,
                        "points":82.96
                    },
                    {
                        "round":8,
                        "points":106.48
                    }
                ]
            },
            {
                "name":"Caio Batista",
                "team":"Batista S.C",
                "points":669.46,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_101/escudo/ea/12/37/006d268f25-c0b7-4761-b3ff-8e3a9d8c0dea20180323201237",
                "details":[
                    {
                        "round":1,
                        "points":58.95
                    },
                    {
                        "round":2,
                        "points":89.08
                    },
                    {
                        "round":3,
                        "points":65.09
                    },
                    {
                        "round":4,
                        "points":68.16
                    },
                    {
                        "round":5,
                        "points":117.52
                    },
                    {
                        "round":6,
                        "points":85.48
                    },
                    {
                        "round":7,
                        "points":84.56
                    },
                    {
                        "round":8,
                        "points":100.62
                    }
                ]
            },
            {
                "name":"Alberto Perdigão",
                "team":"PerdiCartola F.C",
                "points":669.34,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_111/escudo/15/20/00/000fde8b37-3a24-4acb-8e0c-73d41b9ef71520180414132000",
                "details":[
                    {
                        "round":1,
                        "points":73.35
                    },
                    {
                        "round":2,
                        "points":52.08
                    },
                    {
                        "round":3,
                        "points":97.69
                    },
                    {
                        "round":4,
                        "points":51.22
                    },
                    {
                        "round":5,
                        "points":124.22
                    },
                    {
                        "round":6,
                        "points":65.62
                    },
                    {
                        "round":7,
                        "points":90.88
                    },
                    {
                        "round":8,
                        "points":114.28
                    }
                ]
            },
            {
                "name":"Marcelo Pascoal",
                "team":"Celim Team",
                "points":652.52,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/73/08/40/00524fac54-80b2-404a-af8e-685d2d16107320180410140840",
                "details":[
                    {
                        "round":1,
                        "points":74.95
                    },
                    {
                        "round":2,
                        "points":88.14
                    },
                    {
                        "round":3,
                        "points":53.29
                    },
                    {
                        "round":4,
                        "points":71.26
                    },
                    {
                        "round":5,
                        "points":99.82
                    },
                    {
                        "round":6,
                        "points":64.82
                    },
                    {
                        "round":7,
                        "points":64.96
                    },
                    {
                        "round":8,
                        "points":135.28
                    }
                ]
            },
            {
                "name":"Rennan Batista",
                "team":"Chico e Gunha FC",
                "points":648.9,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_101/escudo/51/03/57/003c06ccac-0b0d-4f74-9433-93c51432475120180323220357",
                "details":[
                    {
                        "round":1,
                        "points":81.89
                    },
                    {
                        "round":2,
                        "points":94.28
                    },
                    {
                        "round":3,
                        "points":88.79
                    },
                    {
                        "round":4,
                        "points":35.12
                    },
                    {
                        "round":5,
                        "points":92.22
                    },
                    {
                        "round":6,
                        "points":77.52
                    },
                    {
                        "round":7,
                        "points":77.84
                    },
                    {
                        "round":8,
                        "points":101.24
                    }
                ]
            },
            {
                "name":"Rafael Costa",
                "team":"Ferrimbahçe",
                "points":632.46,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_112/escudo/e6/09/39/001d366c29-9e34-4201-958b-34aa246edfe620180414140939",
                "details":[
                    {
                        "round":1,
                        "points":88.47
                    },
                    {
                        "round":2,
                        "points":77.18
                    },
                    {
                        "round":3,
                        "points":74.09
                    },
                    {
                        "round":4,
                        "points":74.12
                    },
                    {
                        "round":5,
                        "points":94.76
                    },
                    {
                        "round":6,
                        "points":63.98
                    },
                    {
                        "round":7,
                        "points":84.74
                    },
                    {
                        "round":8,
                        "points":75.12
                    }
                ]
            },
            {
                "name":"Vanduy Sales",
                "team":"Vanduka FC",
                "points":627.83,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/5e/46/05/00f08bd7cf-ca3e-4734-871a-e40a53804b5e20180410154605",
                "details":[
                    {
                        "round":1,
                        "points":66.89
                    },
                    {
                        "round":2,
                        "points":61.48
                    },
                    {
                        "round":3,
                        "points":88.49
                    },
                    {
                        "round":4,
                        "points":75.32
                    },
                    {
                        "round":5,
                        "points":89.73
                    },
                    {
                        "round":6,
                        "points":72.09
                    },
                    {
                        "round":7,
                        "points":74.67
                    },
                    {
                        "round":8,
                        "points":99.16
                    }
                ]
            },
            {
                "name":"José Carlos",
                "team":"Boa Viagem E. Clube",
                "points":619.55,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/40/32/34/00bf8f80da-4356-466e-a062-da07b4b1a34020180410103234",
                "details":[
                    {
                        "round":1,
                        "points":68.56
                    },
                    {
                        "round":2,
                        "points":101.99
                    },
                    {
                        "round":3,
                        "points":82.49
                    },
                    {
                        "round":4,
                        "points":44.62
                    },
                    {
                        "round":5,
                        "points":84.92
                    },
                    {
                        "round":6,
                        "points":63.23
                    },
                    {
                        "round":7,
                        "points":77.06
                    },
                    {
                        "round":8,
                        "points":96.68
                    }
                ]
            },
            {
                "name":"Diogo",
                "team":"Cearamengofc",
                "points":611.37,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/9f/10/40/00385df8a3-17fd-4936-a6eb-3270855b619f20180326201040",
                "details":[
                    {
                        "round":1,
                        "points":55.59
                    },
                    {
                        "round":2,
                        "points":99.29
                    },
                    {
                        "round":3,
                        "points":76.96
                    },
                    {
                        "round":4,
                        "points":66.72
                    },
                    {
                        "round":5,
                        "points":113.76
                    },
                    {
                        "round":6,
                        "points":40.39
                    },
                    {
                        "round":7,
                        "points":65.14
                    },
                    {
                        "round":8,
                        "points":93.52
                    }
                ]
            },
            {
                "name":"Emival Queiroz",
                "team":"Emival SCCP",
                "points":610.36,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/19/22/55/00d1e5a05d-2d80-4c88-b431-b30d36594c1920180411162255",
                "details":[
                    {
                        "round":1,
                        "points":60.85
                    },
                    {
                        "round":2,
                        "points":70.38
                    },
                    {
                        "round":3,
                        "points":27.02
                    },
                    {
                        "round":4,
                        "points":48.16
                    },
                    {
                        "round":5,
                        "points":135.23
                    },
                    {
                        "round":6,
                        "points":71.92
                    },
                    {
                        "round":7,
                        "points":83.37
                    },
                    {
                        "round":8,
                        "points":113.43
                    }
                ]
            },
            {
                "name":"Ronilson Costa",
                "team":"Phode Chorarr FC",
                "points":609.78,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_103/escudo/36/36/53/00f3f60de2-60ef-432d-9695-e924b034033620180326233653",
                "details":[
                    {
                        "round":1,
                        "points":105.15
                    },
                    {
                        "round":2,
                        "points":64.95
                    },
                    {
                        "round":3,
                        "points":54.92
                    },
                    {
                        "round":4,
                        "points":73.72
                    },
                    {
                        "round":5,
                        "points":110.32
                    },
                    {
                        "round":6,
                        "points":56.68
                    },
                    {
                        "round":7,
                        "points":61.26
                    },
                    {
                        "round":8,
                        "points":82.78
                    }
                ]
            },
            {
                "name":"Vanderson Cabral",
                "team":"FC Cara Seca",
                "points":608.66,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/58/27/49/0095a2202b-f659-485c-a073-a8708b2d215820180412132749",
                "details":[
                    {
                        "round":1,
                        "points":76.87
                    },
                    {
                        "round":2,
                        "points":59.24
                    },
                    {
                        "round":3,
                        "points":69.94
                    },
                    {
                        "round":4,
                        "points":76.16
                    },
                    {
                        "round":5,
                        "points":93.06
                    },
                    {
                        "round":6,
                        "points":70.82
                    },
                    {
                        "round":7,
                        "points":51.24
                    },
                    {
                        "round":8,
                        "points":111.33
                    }
                ]
            },
            {
                "name":"Victor Santiago",
                "team":"VBSantiago FC",
                "points":604.58,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/82/18/03/001e09f7b4-5047-495a-8634-8d3328be278220180326111803",
                "details":[
                    {
                        "round":1,
                        "points":75.69
                    },
                    {
                        "round":2,
                        "points":81.04
                    },
                    {
                        "round":3,
                        "points":76.79
                    },
                    {
                        "round":4,
                        "points":48.42
                    },
                    {
                        "round":5,
                        "points":97.42
                    },
                    {
                        "round":6,
                        "points":46.83
                    },
                    {
                        "round":7,
                        "points":73.24
                    },
                    {
                        "round":8,
                        "points":105.15
                    }
                ]
            },
            {
                "name":"Messias Cezar",
                "team":"Mumbaba Futebol Clube",
                "points":589.98,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_115/escudo/da/42/10/0080bc5722-e087-4531-a3b0-b3d504455cda20180423114210",
                "details":[
                    {
                        "round":1,
                        "points":62.65
                    },
                    {
                        "round":2,
                        "points":61.19
                    },
                    {
                        "round":3,
                        "points":106.45
                    },
                    {
                        "round":4,
                        "points":66.52
                    },
                    {
                        "round":5,
                        "points":62.63
                    },
                    {
                        "round":6,
                        "points":45.8
                    },
                    {
                        "round":7,
                        "points":78.74
                    },
                    {
                        "round":8,
                        "points":106
                    }
                ]
            },
            {
                "name":"Daniel Oliveira",
                "team":"PIEDADE FCF",
                "points":573.73,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_100/escudo/02/24/25/00a1fc9194-2acd-4579-b6ff-6e936d070b0220180322142425",
                "details":[
                    {
                        "round":1,
                        "points":77.15
                    },
                    {
                        "round":2,
                        "points":84.98
                    },
                    {
                        "round":3,
                        "points":83.89
                    },
                    {
                        "round":4,
                        "points":57.55
                    },
                    {
                        "round":5,
                        "points":90.42
                    },
                    {
                        "round":6,
                        "points":45.77
                    },
                    {
                        "round":7,
                        "points":48.35
                    },
                    {
                        "round":8,
                        "points":85.62
                    }
                ]
            },
            {
                "name":"Victor Bessa",
                "team":"Bessa CSC",
                "points":567.69,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/dc/33/02/00ce9bd458-5b83-48c7-a0c0-a4710fc141dc20180411103302",
                "details":[
                    {
                        "round":1,
                        "points":62.77
                    },
                    {
                        "round":2,
                        "points":74.85
                    },
                    {
                        "round":3,
                        "points":45.05
                    },
                    {
                        "round":4,
                        "points":57.42
                    },
                    {
                        "round":5,
                        "points":112.46
                    },
                    {
                        "round":6,
                        "points":52.19
                    },
                    {
                        "round":7,
                        "points":75.06
                    },
                    {
                        "round":8,
                        "points":87.89
                    }
                ]
            },
            {
                "name":"Daniel Zanata",
                "team":"Zanatinha CFC",
                "points":563.84,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_109/escudo/0a/02/08/00cf4297dc-6402-466b-b246-8a46ee20d50a20180412160208",
                "details":[
                    {
                        "round":1,
                        "points":88.55
                    },
                    {
                        "round":2,
                        "points":68.75
                    },
                    {
                        "round":3,
                        "points":49.35
                    },
                    {
                        "round":4,
                        "points":80.02
                    },
                    {
                        "round":5,
                        "points":64.82
                    },
                    {
                        "round":6,
                        "points":57.03
                    },
                    {
                        "round":7,
                        "points":47.94
                    },
                    {
                        "round":8,
                        "points":107.38
                    }
                ]
            },
            {
                "name":"Lucas Batista",
                "team":"vovo S.C",
                "points":558.76,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/f6/17/23/00b142cb5a-fdfd-4976-875a-89e6a21cdef620180324211723",
                "details":[
                    {
                        "round":1,
                        "points":69.79
                    },
                    {
                        "round":2,
                        "points":77.48
                    },
                    {
                        "round":3,
                        "points":39.65
                    },
                    {
                        "round":4,
                        "points":53.02
                    },
                    {
                        "round":5,
                        "points":99.52
                    },
                    {
                        "round":6,
                        "points":73.78
                    },
                    {
                        "round":7,
                        "points":90.74
                    },
                    {
                        "round":8,
                        "points":54.78
                    }
                ]
            },
            {
                "name":"Cayo Luiz",
                "team":"C.Luiz",
                "points":544,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/f4/51/23/003ad7972e-c85d-4ea0-a979-f373c9815ff420180326185123",
                "details":[
                    {
                        "round":1,
                        "points":53.77
                    },
                    {
                        "round":2,
                        "points":60.28
                    },
                    {
                        "round":3,
                        "points":64.35
                    },
                    {
                        "round":4,
                        "points":92.88
                    },
                    {
                        "round":5,
                        "points":57.66
                    },
                    {
                        "round":6,
                        "points":87.12
                    },
                    {
                        "round":7,
                        "points":64.76
                    },
                    {
                        "round":8,
                        "points":63.18
                    }
                ]
            },
            {
                "name":"Fabio Gurgel",
                "team":"FaBayern FC",
                "points":540.7,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/62/39/50/0067cbf8fd-a20c-499e-bef5-f0f5c0ce5b6220180411153950",
                "details":[
                    {
                        "round":1,
                        "points":77.15
                    },
                    {
                        "round":2,
                        "points":60.58
                    },
                    {
                        "round":3,
                        "points":45.29
                    },
                    {
                        "round":4,
                        "points":21.37
                    },
                    {
                        "round":5,
                        "points":95.92
                    },
                    {
                        "round":6,
                        "points":71.53
                    },
                    {
                        "round":7,
                        "points":91.56
                    },
                    {
                        "round":8,
                        "points":77.3
                    }
                ]
            },
            {
                "name":"Elano Matos",
                "team":"Pau Serrado FC",
                "points":534.69,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/82/02/44/007f184c56-0ccd-4ad9-b966-1be4c2af158220180413170244",
                "details":[
                    {
                        "round":1,
                        "points":78.02
                    },
                    {
                        "round":2,
                        "points":57.34
                    },
                    {
                        "round":3,
                        "points":45.95
                    },
                    {
                        "round":4,
                        "points":54.62
                    },
                    {
                        "round":5,
                        "points":71.16
                    },
                    {
                        "round":6,
                        "points":91.12
                    },
                    {
                        "round":7,
                        "points":42.26
                    },
                    {
                        "round":8,
                        "points":94.22
                    }
                ]
            },
            {
                "name":"JORGE PEREIRA",
                "team":"JORGEJOH",
                "points":518.55,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_108/escudo/aa/17/03/007dbfde16-dee2-4a0a-abf1-f1f3eedcaaaa20180412131703",
                "details":[
                    {
                        "round":1,
                        "points":59.05
                    },
                    {
                        "round":2,
                        "points":71.68
                    },
                    {
                        "round":3,
                        "points":19.49
                    },
                    {
                        "round":4,
                        "points":54.47
                    },
                    {
                        "round":5,
                        "points":98.26
                    },
                    {
                        "round":6,
                        "points":65.06
                    },
                    {
                        "round":7,
                        "points":78.16
                    },
                    {
                        "round":8,
                        "points":72.38
                    }
                ]
            },
            {
                "name":"Felipe Phelype",
                "team":"IslandOfCatsFootball",
                "points":500.76,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_102/escudo/3b/30/52/00e363677a-d283-48b2-8f1a-97fee1ada03b20180326223052",
                "details":[
                    {
                        "round":1,
                        "points":40.25
                    },
                    {
                        "round":2,
                        "points":57.14
                    },
                    {
                        "round":3,
                        "points":29.49
                    },
                    {
                        "round":4,
                        "points":64.42
                    },
                    {
                        "round":5,
                        "points":88.92
                    },
                    {
                        "round":6,
                        "points":41.28
                    },
                    {
                        "round":7,
                        "points":69.38
                    },
                    {
                        "round":8,
                        "points":109.88
                    }
                ]
            },
            {
                "name":"Daniel Mendes",
                "team":"djmss fc",
                "points":482.83,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/01/40/51/003bc5bc37-a9f7-4c4c-a152-ed225a60d20120180410144051",
                "details":[
                    {
                        "round":1,
                        "points":28.05
                    },
                    {
                        "round":2,
                        "points":35.79
                    },
                    {
                        "round":3,
                        "points":47.42
                    },
                    {
                        "round":4,
                        "points":85.92
                    },
                    {
                        "round":5,
                        "points":75.52
                    },
                    {
                        "round":6,
                        "points":90.52
                    },
                    {
                        "round":7,
                        "points":65.03
                    },
                    {
                        "round":8,
                        "points":54.58
                    }
                ]
            },
            {
                "name":"Paulo Cristiano",
                "team":"Ragnar Lothbrok 2018",
                "points":481.42,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_107/escudo/9e/48/55/00c8ee0c6a-37ab-40ea-8a28-9b8be9b8649e20180411094855",
                "details":[
                    {
                        "round":1,
                        "points":54.75
                    },
                    {
                        "round":2,
                        "points":49.68
                    },
                    {
                        "round":3,
                        "points":58.39
                    },
                    {
                        "round":4,
                        "points":67.82
                    },
                    {
                        "round":5,
                        "points":82.52
                    },
                    {
                        "round":6,
                        "points":77.32
                    },
                    {
                        "round":7,
                        "points":32.76
                    },
                    {
                        "round":8,
                        "points":58.18
                    }
                ]
            },
            {
                "name":"Renan Benevides",
                "team":"simple man",
                "points":467.6,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/a5/56/39/0019f298fb-4fc9-47d2-a8e6-b944682db5a520180413145639",
                "details":[
                    {
                        "round":1,
                        "points":60.16
                    },
                    {
                        "round":2,
                        "points":45.68
                    },
                    {
                        "round":3,
                        "points":44.24
                    },
                    {
                        "round":4,
                        "points":116.46
                    },
                    {
                        "round":5,
                        "points":81.52
                    },
                    {
                        "round":6,
                        "points":69.72
                    },
                    {
                        "round":7,
                        "points":9.04
                    },
                    {
                        "round":8,
                        "points":40.78
                    }
                ]
            },
            {
                "name":"Marcelo Almeida",
                "team":"Camisa10daGavea",
                "points":466.56,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_109/escudo/cd/38/52/0088e74e4f-f38a-4256-8c47-0179c02643cd20180412183852",
                "details":[
                    {
                        "round":1,
                        "points":73.29
                    },
                    {
                        "round":2,
                        "points":87.99
                    },
                    {
                        "round":3,
                        "points":23.62
                    },
                    {
                        "round":4,
                        "points":51.13
                    },
                    {
                        "round":5,
                        "points":52.53
                    },
                    {
                        "round":6,
                        "points":74.33
                    },
                    {
                        "round":7,
                        "points":56.92
                    },
                    {
                        "round":8,
                        "points":46.75
                    }
                ]
            },
            {
                "name":"Márcio Fernandes",
                "team":"Gigante Alvinegro MF",
                "points":450.91,
                "team_symbol":"https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_110/escudo/3b/42/24/00cd21c39d-27f3-453f-96eb-de0bf4c9d13b20180413164224",
                "details":[
                    {
                        "round":1,
                        "points":43.79
                    },
                    {
                        "round":2,
                        "points":74.34
                    },
                    {
                        "round":3,
                        "points":53.85
                    },
                    {
                        "round":4,
                        "points":57.32
                    },
                    {
                        "round":5,
                        "points":53.17
                    },
                    {
                        "round":6,
                        "points":73.73
                    },
                    {
                        "round":7,
                        "points":50.38
                    },
                    {
                        "round":8,
                        "points":44.33
                    }
                ]
            }
        ]
    }
];
